DELIMITER //

CREATE PROCEDURE `aqintegrations`.`p_uimp1_prepwork`()
BEGIN
	TRUNCATE TABLE uimp_usergroupassignment;
    TRUNCATE TABLE uimp_requesterupdateerror;
	TRUNCATE TABLE uimp_rawdata;
	
	DROP Table `aqintegrations`.`uimp_aqreserveuserdata`;
	DROP Table `aqintegrations`.`uimp_aqreserveprocess`;
	DROP Table `aqintegrations`.`uimp_requesterupdate`;
		

	CREATE TABLE IF NOT EXISTS `aqintegrations`.`uimp_requesterupdate` (
	  `empliD` VARCHAR(50) NULL,
	  `ntuserid` VARCHAR(50) NULL,
	  `firstname` VARCHAR(50) NULL,
	  `preferredname` VARCHAR(100) NULL,
	  `middleinitial` VARCHAR(5) NULL,
	  `lastname` VARCHAR(50) NULL,
	  `email` VARCHAR(256) NULL,
	  `saml` VARCHAR(256) NULL,
	  `title` VARCHAR (100) NULL,
	  `department` VARCHAR (50) NULL,
	  `businessunit` VARCHAR (50) NULL,
	  `organizationcode` VARCHAR(150) NULL,
	  `workphone` VARCHAR (50) NULL,
	  `mobilephone` VARCHAR (25) NULL,
	  `employeeid` VARCHAR (50) NULL, 
	  `location` VARCHAR (256) NULL,   
	  `reservelocation` VARCHAR (256) NULL, 
	  `language` VARCHAR (100) NULL,
	  `userrole` VARCHAR (100) NULL,
	  `sysidRole` BIGINT NULL,
	  `sysidLanguage` BIGINT NULL,
	  `sysidDepartment` BIGINT NULL,
	  `sysidTitle` BIGINT NULL,
	  `sysidBusinessUnit` BIGINT NULL,
	  `sysidManager` BIGINT NULL,
	  `sysidUserStatus` INT NULL,
	  `locationId` BIGINT NULL,
	  `badge` VARCHAR(50) NULL,
	  `status` VARCHAR(50) NULL,
	  `usergroups` TEXT NULL,
	  INDEX `IX_RequesteUpdate_EMPLID` (`emplid` ASC, `Email` ASC));


	CREATE TABLE IF NOT EXISTS `aqintegrations`.`uimp_aqreserveuserdata` (
	  `SYSID_ApplicationUser` BIGINT NOT NULL,
	  `LASTNAME` VARCHAR(50) NULL,
	  `FIRSTNAME` VARCHAR(50) NULL,
	  `MIDDLEINITIAL` VARCHAR(50) NULL,
	  `PREFERREDNAME` VARCHAR(100) NULL,
	  `PRIMARYEMAILADDRESS` VARCHAR(256) NULL,
	  `STATUS` VARCHAR(20) NULL,
	  `PRIVATEPROFILE` VARCHAR(10) NULL,
	  `LANGUAGE` VARCHAR(65) NULL,
	  `LOCATION` VARCHAR(256) NULL,
	  `DEPARTMENT` VARCHAR(100) NULL,
	  `TITLE` VARCHAR(100) NULL,
	  `WORKPHONE` VARCHAR(64) NULL,
	  `MOBILEPHONE` VARCHAR(50) NULL,
	  `ADDITIONALEMAIL` VARCHAR(100) NULL,
	  `USERROLE` VARCHAR(50) NULL,
	  `USERGROUPS` TEXT NULL,
	  `BADGE` VARCHAR(50) NULL,
	  `SAML` VARCHAR(256) NULL,
	  `MAXDAYSINADVANCE` VARCHAR(10) NULL,
	  `MAXWORKSPACERESERVATIONS` VARCHAR(10) NULL,
	  `BUMP` VARCHAR(10) NULL,
	  `MAKEASSETSAVAILABLEBUMP` VARCHAR(10) NULL,
	  `AUTOBUMP` VARCHAR(10) NULL,
	  `MAKEASSETSAVAILABLEAUTOBUMP` VARCHAR(10) NULL,
	  `GAPCONFLICTING` VARCHAR(10) NULL,
	  `LOCATIONPREFERENCE` VARCHAR(50) NULL,
	  `ASSETCATEGORYPREFERENCE` VARCHAR(50) NULL,
	  `PHONEINFORMATION` TEXT NULL,
	  `ORGANIZATIONCODE` VARCHAR(255) NULL,
	  `EMPLOYEEID` VARCHAR(255) NULL,
	  `BUSINESSUNIT` VARCHAR (100)  NULL,
	  `PRIMARYWORKSPACE` VARCHAR (100) NULL,
	  `PRIMARYWORKSPACELOCATION` TEXT NULL,
	  `MAXWORKSPACEDAYSWEEKALLOWED` VARCHAR (10) NULL,
	  `RECEIVERESERVATIONCONFIRMATION` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONUPDATED` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONREMINDER` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELED` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELEDBYADMINUSERORBYTHEAPPLICATION` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELEDBYAPPLICATIONDUETOFAILURETOCHECKIN` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELLATIONWARNING` VARCHAR(10) NULL,
	  `RECEIVEREQUESTAPPROVED` VARCHAR(10) NULL,
	  `RECEIVEREQUESTDENIED` VARCHAR(10) NULL,
	  `RECEIVECHECKINSUCCESSFUL_FORPRESENCEEVENTSONLY` VARCHAR(10) NULL,
	  `sysidRole` BIGINT NULL,
	  `sysidLanguage` BIGINT NULL,
	  `sysidDepartment` BIGINT NULL,
	  `sysidTitle` BIGINT NULL,
	  `sysidBusinessUnit` BIGINT NULL,
	  `sysidManager` BIGINT NULL,
	  `sysidAccount` BIGINT NULL,
	  `originaluser` VARCHAR (10) NULL,
	  `comments` TEXT NULL,
	  `address1` VARCHAR (512) NULL,
	  `address2` VARCHAR (512) NULL,
	  `city` VARCHAR (256) NULL,
	  `state_province` VARCHAR (256) NULL,
	  `postalcode` VARCHAR (50) NULL,
	  `country` VARCHAR (256) NULL,
	  `sysidDefaultCategory` BIGINT NULL,
	  `sysidDefaultResType` BIGINT NULL,
	  `defaultChargeCode` VARCHAR (256) NULL,
	  `calendarURL` TEXT NULL,
	  `statusMessage` TEXT NULL,
	  `userEmailPreferences` TEXT NULL,
	  `userImages` TEXT NULL,
	  `userContacts` TEXT NULL,
	  `userCredentials` TEXT NULL,  
	  `userAttributeValue` TEXT NULL,  
	  `mypeople` TEXT NULL,
	  `myrooms`  TEXT NULL,
	  `myDelegates` TEXT NULL,
	  `preferences` TEXT NULL,
	  `userAuthRules` TEXT NULL,
	  `sysidUserStatus` INT NULL,
	  `userPassword` VARCHAR (256) NULL,
	  `accountLocked` VARCHAR (20) NULL,
	  `sysidDefaultLocation` BIGINT NULL,
	  `sysidHomeLocation` BIGINT NULL,
	  `forums` TEXT NULL,
	  `aqPasswordExpDate` TEXT NULL,
	  `groupMemberships` TEXT NULL,
	  `sysidSAMLUserCredential` BIGINT NULL,
	  `sysidBadgeUserCredential` BIGINT NULL,
	  `sysidOrgCodeUserAttribute` BIGINT NULL,
	  `sysidEmplIDUserAttribute`  BIGINT NULL,
	  `reservationSpendingLimit`  BIGINT NULL);


	CREATE TABLE IF NOT EXISTS `aqintegrations`.`uimp_aqreserveprocess` (
	  `BatchID` INT NOT NULL,
	  `EMPLID` VARCHAR(50) NULL,
	  `SYSID_ApplicationUser` BIGINT NOT NULL,
	  `NTUSERID` VARCHAR(50) NULL,
	  `FirstName` VARCHAR(50) NOT NULL,
	  `MiddleInitial` VARCHAR(50) NULL,
	  `LastName` VARCHAR(50) NOT NULL,
	  `PreferredName` VARCHAR(100) NULL,
	  `Email` VARCHAR(256) NOT NULL,
	  `PRIVATEPROFILE` VARCHAR(10) NULL,
	  `LANGUAGE` VARCHAR(65) NULL,
	  `LOCATION` VARCHAR(256) NULL,
	  `DEPARTMENT` VARCHAR(100) NULL,
	  `TITLE` VARCHAR(100) NULL,
	  `WORKPHONE` VARCHAR(64) NULL,
	  `MOBILEPHONE` VARCHAR(50) NULL,
	  `ADDITIONALEMAIL` VARCHAR(100) NULL,
	  `USERROLE` VARCHAR(50) NULL,
	  `USERGROUPS` TEXT NULL,
	  `BADGE` VARCHAR(50) NULL,
	  `SAML` VARCHAR(256) NULL,
	  `MAXDAYSINADVANCE` VARCHAR(10) NULL,
	  `MAXWORKSPACERESERVATIONS` VARCHAR(10) NULL,
	  `BUMP` VARCHAR(10) NULL,
	  `MAKEASSETSAVAILABLEBUMP` VARCHAR(10) NULL,
	  `AUTOBUMP` VARCHAR(10) NULL,
	  `MAKEASSETSAVAILABLEAUTOBUMP` VARCHAR(10) NULL,
	  `GAPCONFLICTING` VARCHAR(10) NULL,
	  `LOCATIONPREFERENCE` VARCHAR(50) NULL,
	  `ASSETCATEGORYPREFERENCE` VARCHAR(50) NULL,
	  `PHONEINFORMATION` VARCHAR(0) NULL,
	  `ORGANIZATIONCODE` VARCHAR(255) NULL,
	  `EMPLOYEEID` VARCHAR(255) NULL,
	  `BUSINESSUNIT` VARCHAR (100)  NULL,
	  `PRIMARYWORKSPACE` VARCHAR (100) NULL,
	  `PRIMARYWORKSPACELOCATION` TEXT NULL,
	  `MAXWORKSPACEDAYSWEEKALLOWED` VARCHAR (10) NULL,
	  `RECEIVERESERVATIONCONFIRMATION` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONUPDATED` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONREMINDER` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELED` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELEDBYADMINUSERORBYTHEAPPLICATION` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELEDBYAPPLICATIONDUETOFAILURETOCHECKIN` VARCHAR(10) NULL,
	  `RECEIVERESERVATIONCANCELLATIONWARNING` VARCHAR(10) NULL,
	  `RECEIVEREQUESTAPPROVED` VARCHAR(10) NULL,
	  `RECEIVEREQUESTDENIED` VARCHAR(10) NULL,
	  `RECEIVECHECKINSUCCESSFUL_FORPRESENCEEVENTSONLY` VARCHAR(10) NULL,
	  `Password` VARCHAR(50) NULL,
	  `Status` VARCHAR(20) NOT NULL,
	  `sysidRole` BIGINT NULL,
	  `sysidLanguage` BIGINT NULL,
	  `sysidDepartment` BIGINT NULL,
	  `sysidTitle` BIGINT NULL,
	  `sysidBusinessUnit` BIGINT NULL,
	  `sysidManager` BIGINT NULL,
	  `sysidAccount` BIGINT NULL,
	  `originaluser` VARCHAR (10) NULL,
	  `comments` TEXT NULL,
	  `address1` VARCHAR (512) NULL,
	  `address2` VARCHAR (512) NULL,
	  `city` VARCHAR (256) NULL,
	  `state_province` VARCHAR (256) NULL,
	  `postalcode` VARCHAR (50) NULL,
	  `country` VARCHAR (256) NULL,
	  `sysidDefaultCategory` BIGINT NULL,
	  `sysidDefaultResType` BIGINT NULL,
	  `defaultChargeCode` VARCHAR (256) NULL,
	  `calendarURL` TEXT NULL,
	  `statusMessage` TEXT NULL,
	  `userEmailPreferences` TEXT NULL,
	  `userImages` TEXT NULL,
	  `userContacts` TEXT NULL,
	  `userCredentials` TEXT NULL,
	  `userAttributeValue` TEXT NULL,    
	  `mypeople` TEXT NULL,
	  `myrooms`  TEXT NULL,
	  `myDelegates` TEXT NULL,
	  `preferences` TEXT NULL,
	  `userAuthRules` TEXT NULL,
	  `sysidUserStatus` INT NULL,
	  `userPassword` VARCHAR (256) NULL,
	  `accountLocked` VARCHAR (20) NULL,
	  `sysidDefaultLocation` BIGINT NULL,
	  `sysidHomeLocation` BIGINT NULL,
	  `forums` TEXT NULL,
	  `aqPasswordExpDate` VARCHAR (256) NULL,
	  `groupMemberships` TEXT NULL,
	  `sysidSAMLUserCredential` BIGINT NULL,
	  `sysidBadgeUserCredential` BIGINT NULL,
	  `sysidOrgCodeUserAttribute` BIGINT NULL,
	  `sysidEmplIDUserAttribute`  BIGINT NULL,
	  `reservationSpendingLimit`  BIGINT NULL,
	  `Action` BIGINT NOT NULL,
	  `ActionStatus` CHAR(1) NULL,
	  `ErrorMessage` VARCHAR(1000) NULL);

END //

DELIMITER ;
